workflows:
  # Workflow para iOS
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Navigate to Flutter project
        script: | 
          cd frontend
      - name: Get Flutter packages
        script: | 
          cd frontend
          flutter pub get
      - name: Flutter analyze
        script: | 
          cd frontend
          flutter analyze
      - name: Flutter unit tests
        script: | 
          cd frontend
          flutter test
        ignore_failure: true
      - name: Build iOS IPA (Development)
        script: | 
          cd frontend
          flutter build ios --release --no-codesign
    artifacts:
      - frontend/build/ios/Release-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - rasoky22@gmail.com
        notify:
          success: true
          failure: true
