<?php

namespace App\Enums;

enum ErrorCodesEnum: string
{
  case CLIENT_ERROR = 'CLIENT_ERROR';
  case BAD_REQUEST = 'BAD_REQUEST';
  case UNAUTHORIZED = 'UNAUTHORIZED';
  case FORBIDDEN = 'FORBIDDEN';
  case INVALID_SIGNED_URL = 'INVALID_SIGNED_URL';
  case NOT_FOUND = 'NOT_FOUND';
  case VALIDATION_ERROR = 'VALIDATION_ERROR';
  case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
  case CORS_ERROR = 'CORS_ERROR';
  case UNHANDLED_EXCEPTION = 'UNHANDLED_EXCEPTION';
  case SERVER_ERROR = 'SERVER_ERROR';
  case NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
}
