// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzzwuJFrtHI-yA_gHvaJsRs7Inwbr7sOs',
    appId: '1:565098481245:web:870b8d6a887cd83b0e2fb4',
    messagingSenderId: '565098481245',
    projectId: 'med-rush-fcm',
    authDomain: 'med-rush-fcm.firebaseapp.com',
    storageBucket: 'med-rush-fcm.firebasestorage.app',
    measurementId: 'G-8G1FD745N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArSKv5PMjkHP26YIOZfczzAEo2266FVhE',
    appId: '1:565098481245:android:087a6a4fe29941130e2fb4',
    messagingSenderId: '565098481245',
    projectId: 'med-rush-fcm',
    storageBucket: 'med-rush-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArSKv5PMjkHP26YIOZfczzAEo2266FVhE',
    appId: '1:565098481245:ios:your-ios-app-id',
    messagingSenderId: '565098481245',
    projectId: 'med-rush-fcm',
    storageBucket: 'med-rush-fcm.firebasestorage.app',
    iosBundleId: 'com.medrushapp.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArSKv5PMjkHP26YIOZfczzAEo2266FVhE',
    appId: '1:565098481245:macos:your-macos-app-id',
    messagingSenderId: '565098481245',
    projectId: 'med-rush-fcm',
    storageBucket: 'med-rush-fcm.firebasestorage.app',
    iosBundleId: 'com.medrushapp.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSKv5PMjkHP26YIOZfczzAEo2266FVhE',
    appId: '1:565098481245:windows:your-windows-app-id',
    messagingSenderId: '565098481245',
    projectId: 'med-rush-fcm',
    authDomain: 'med-rush-fcm.firebaseapp.com',
    storageBucket: 'med-rush-fcm.firebasestorage.app',
  );
}
